### ISSUE TITLE
Homework-1 and 2

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [Abhilash3/Javascript-Assignments#1]
Homework-1
**RentalCarCost**
1. Have proper braces for readability of the conditional logic's in below line of code.
     days * PER_DAY - (GE(days, 7) && 50 || GE(days, 3) && 20 || 0);

Homework-2
**MiddleCharacter**
1. Have proper braces for readability of the conditional logic's in below line of code.
    str.length % 2 && str[n] || str[n - 1].concat(str[n]);

**worldCount**
1. use '===' on conditional comparisons to match with the type&value,  instead of using '==' which checks only value.
2. Better to have only one return statement inside a function block.

Homework-3
1. Add comments for better understanding and readability purpose.

**Comment by Abhilash3** [comment]
RentalCarCost
proper braces: the comment explains the intent and behavior of the expression.

BiddleCharacter
proper braces: and/or expression (left to right) is easy to understand even without braces.

wordCount
use '===': length property for strings is expected to have a numeric value 
one return statement: change implemented

Homework 3
add comments: change implemented

**Comment by maheshbhuvanagiri** [comment]
changes looks good..thankq
